### ISSUE TITLE
Only works with the X432R fork of DeSmuME

### ISSUE THREAD

**Issue by ghost** [StarPants128/ToxInput#3]
Because of this, you can't play Super Mario 64 DS in widescreen. Please update the app to support DeSmuME:

http://desmume.org/download/

**Comment by ninjaraven** [comment]
![image](https://user-images.githubusercontent.com/58012953/139152324-95d26dcd-c9d2-4353-a2c5-02d7d0c67b83.png)

**Comment by pants64DS** [comment]
Since all of ToxInput's features will be included in SM64DS Online, which will support more than one emulator, I'm not planning to update this anymore. Besides, I don't think the widescreen hack works with the European version of SM64DS so you couldn't play it with ToxInput anyway. Since SM64DS Online will have a lot more features that require interfacing with the game's code, it probably won't have support for multiple ROM versions either.

**Comment by ghost** [comment]
Thank you for the knowledge and thank you for your work on this! Do you know where I can go to keep up to date on SM64DS Online?

**Comment by pants64DS** [comment]
It's been on a pause for a while since I've been working on another big project but once I continue working on it, I'll most likely post updates in the SM64DS hacking discord server https://discord.gg/NRfrYbm and eventually on my youtube channel https://www.youtube.com/channel/UCpcw4LOjp9jeaP00GkDa63g
